# Generated by Django 6.0.3 on 2026-03-07 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Penta, BCG, MMR', max_length=100, unique=True)),
                ('live', models.BooleanField(default=False, help_text='Is this a live attenuated vaccine?')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubstitutionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(help_text="Rules for substitution, e.g., 'If age > 1 year'")),
                ('substitute_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes_for', to='vaccines.vaccine')),
                ('target_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_by', to='vaccines.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='CatchupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age_days', models.PositiveIntegerField(help_text='Start of age band for this rule in days')),
                ('max_age_days', models.PositiveIntegerField(help_text='End of age band for this rule in days')),
                ('prior_doses', models.PositiveIntegerField(help_text='Number of doses received so far')),
                ('doses_required', models.PositiveIntegerField(help_text='Total doses required to complete schedule in this catchup scenario')),
                ('min_interval_days', models.PositiveIntegerField(help_text='Minimum interval from previous dose in days')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catchup_rules', to='vaccines.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField(help_text='1 for first dose, 2 for second, etc.')),
                ('min_age_days', models.PositiveIntegerField(help_text='Minimum age in days to receive this dose')),
                ('recommended_age_days', models.PositiveIntegerField(help_text='Recommended age in days')),
                ('max_age_days', models.PositiveIntegerField(blank=True, help_text='Maximum age in days (optional)', null=True)),
                ('min_interval_days', models.PositiveIntegerField(default=0, help_text='Minimum interval from previous dose in days. 0 for first dose.')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rules', to='vaccines.vaccine')),
            ],
            options={
                'ordering': ['vaccine', 'dose_number'],
                'unique_together': {('vaccine', 'dose_number')},
            },
        ),
    ]
