# Generated by Django 6.0.3 on 2026-03-08 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., DTP Family', max_length=100, unique=True)),
                ('min_valid_interval_days', models.PositiveIntegerField(default=28, help_text='Absolute minimum valid interval between ANY two vaccines in this group')),
                ('vaccines', models.ManyToManyField(related_name='groups', to='vaccines.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prior_doses', models.PositiveIntegerField(help_text='Number of valid doses already received from this group')),
                ('min_age_days', models.PositiveIntegerField(help_text='Minimum age in days for this rule to apply')),
                ('max_age_days', models.PositiveIntegerField(blank=True, help_text='Maximum age in days (optional)', null=True)),
                ('min_interval_days', models.PositiveIntegerField(help_text='Minimum interval from the last dose in the group in days')),
                ('vaccine_to_give', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vaccines.vaccine')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vaccines.vaccinegroup')),
            ],
            options={
                'ordering': ['group', 'prior_doses', 'min_age_days'],
            },
        ),
    ]
