# Generated by Django 6.0.3 on 2026-03-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_vaccinegroup_grouprule'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprule',
            name='min_eligible_age_days',
            field=models.PositiveIntegerField(default=0, help_text='Absolute minimum age (days) the child must be to receive this dose. Dose given before this is flagged too_early.'),
        ),
        migrations.AlterField(
            model_name='grouprule',
            name='max_age_days',
            field=models.PositiveIntegerField(blank=True, help_text="Maximum age in days for this rule's age bracket (optional)", null=True),
        ),
        migrations.AlterField(
            model_name='grouprule',
            name='min_age_days',
            field=models.PositiveIntegerField(help_text='Minimum age in days for this rule to apply (age-bracket selector)'),
        ),
    ]
