# Generated by Django 6.0.3 on 2026-03-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0003_grouprule_min_eligible_age_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprule',
            name='min_eligible_age_days',
        ),
    ]
