# Generated by Django 6.0.3 on 2026-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0004_remove_grouprule_min_eligible_age_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerule',
            name='alternate_dose_age_days',
            field=models.PositiveIntegerField(blank=True, help_text='Age in days to switch to alternate dose amount', null=True),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='alternate_dose_amount',
            field=models.CharField(blank=True, help_text='e.g., 0.1ml', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='dose_amount',
            field=models.CharField(blank=True, help_text='e.g., 0.05ml', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='overdue_age_days',
            field=models.PositiveIntegerField(blank=True, help_text='Age in days after which the dose is considered overdue/missing', null=True),
        ),
        migrations.AlterField(
            model_name='catchuprule',
            name='doses_required',
            field=models.PositiveIntegerField(help_text='Total doses needed to complete catch-up'),
        ),
        migrations.AlterField(
            model_name='catchuprule',
            name='max_age_days',
            field=models.PositiveIntegerField(help_text='End of age band in days (e.g., 5 years = 1825 days)'),
        ),
        migrations.AlterField(
            model_name='catchuprule',
            name='min_age_days',
            field=models.PositiveIntegerField(help_text='Start of age band in days (e.g., 1 year = 365 days)'),
        ),
        migrations.AlterField(
            model_name='catchuprule',
            name='min_interval_days',
            field=models.PositiveIntegerField(help_text='Minimum days between catch-up doses'),
        ),
        migrations.AlterField(
            model_name='catchuprule',
            name='prior_doses',
            field=models.PositiveIntegerField(help_text='Number of valid doses received so far'),
        ),
        migrations.AlterField(
            model_name='grouprule',
            name='max_age_days',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum age in days (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='grouprule',
            name='min_age_days',
            field=models.PositiveIntegerField(help_text='Minimum age in days for this rule to apply'),
        ),
        migrations.AlterField(
            model_name='grouprule',
            name='min_interval_days',
            field=models.PositiveIntegerField(help_text='Minimum days from the last dose in the group'),
        ),
        migrations.AlterField(
            model_name='grouprule',
            name='prior_doses',
            field=models.PositiveIntegerField(help_text='Number of valid group doses already received'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='max_age_days',
            field=models.PositiveIntegerField(blank=True, help_text='Latest allowed age in days (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='min_age_days',
            field=models.PositiveIntegerField(help_text='Minimum age in days (e.g., 6 weeks = 42 days, 9 months = 270 days)'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='min_interval_days',
            field=models.PositiveIntegerField(default=0, help_text='Min days since previous dose. Use 0 for first dose.'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='recommended_age_days',
            field=models.PositiveIntegerField(help_text='Ideal age in days to receive this dose'),
        ),
    ]
