# Generated by Django 6.0.3 on 2026-03-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0005_schedulerule_alternate_dose_age_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulerule',
            name='alternate_dose_age_days',
        ),
        migrations.RemoveField(
            model_name='schedulerule',
            name='alternate_dose_amount',
        ),
        migrations.AddField(
            model_name='catchuprule',
            name='dose_amount',
            field=models.CharField(blank=True, help_text='Override dose amount for this catch-up rule', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grouprule',
            name='dose_amount',
            field=models.CharField(blank=True, help_text='Dose amount for this specific group rule', max_length=50, null=True),
        ),
    ]
