# Generated by Django 6.0.3 on 2026-03-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0006_remove_schedulerule_alternate_dose_age_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='compatible_live_vaccines',
            field=models.ManyToManyField(blank=True, help_text='Other live vaccines that can be given safely within 28 days (e.g. OPV)', to='vaccines.vaccine'),
        ),
    ]
