# Generated by Django 6.0.3 on 2026-03-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0007_vaccine_compatible_live_vaccines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('vaccine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_profile', to='vaccines.vaccine')),
            ],
            options={
                'ordering': ['vaccine__name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('min_valid_interval_days', models.PositiveIntegerField(default=28, help_text='Absolute minimum valid interval between any two doses in this series')),
                ('mixing_policy', models.CharField(choices=[('strict', 'Strict product continuity'), ('age_rule', 'Age-based product switching'), ('flexible', 'Flexible switching')], default='age_rule', max_length=20)),
                ('legacy_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_policy', to='vaccines.vaccinegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeriesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_series_links', to='vaccines.product')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_products', to='vaccines.series')),
            ],
            options={
                'ordering': ['series', 'priority', 'product__vaccine__name'],
                'unique_together': {('series', 'product')},
            },
        ),
        migrations.AddField(
            model_name='series',
            name='products',
            field=models.ManyToManyField(related_name='series_memberships', through='vaccines.SeriesProduct', to='vaccines.product'),
        ),
        migrations.CreateModel(
            name='SeriesRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(help_text='1 for first dose slot, 2 for second, etc.')),
                ('prior_valid_doses', models.PositiveIntegerField(help_text='Number of valid series doses already received')),
                ('min_age_days', models.PositiveIntegerField(help_text='Minimum age in days for this slot rule')),
                ('recommended_age_days', models.PositiveIntegerField(help_text='Target age in days for this slot rule')),
                ('overdue_age_days', models.PositiveIntegerField(blank=True, help_text='Age in days when the slot becomes missing', null=True)),
                ('max_age_days', models.PositiveIntegerField(blank=True, help_text='Maximum age in days (optional)', null=True)),
                ('min_interval_days', models.PositiveIntegerField(help_text='Minimum days from the previous valid series dose')),
                ('dose_amount', models.CharField(blank=True, help_text='Dose amount for this slot rule', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_rules', to='vaccines.product')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vaccines.series')),
            ],
            options={
                'ordering': ['series', 'prior_valid_doses', 'min_age_days', 'slot_number'],
            },
        ),
    ]
