# Generated by Django 6.0.3 on 2026-03-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0009_backfill_series_policy_from_legacy_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Whether this product is currently available for scheduling'),
        ),
        migrations.CreateModel(
            name='DependencyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_slot_number', models.PositiveIntegerField(blank=True, help_text='Leave blank to apply to every slot in the dependent series', null=True)),
                ('anchor_slot_number', models.PositiveIntegerField(blank=True, help_text='Leave blank to use the same slot number as the dependent series', null=True)),
                ('min_offset_days', models.PositiveIntegerField(default=0, help_text='Minimum days after the anchor slot')),
                ('block_if_anchor_missing', models.BooleanField(default=True, help_text='If enabled, the dependent slot stays blocked until the anchor slot exists')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('anchor_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchored_dependency_rules', to='vaccines.series')),
                ('dependent_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_rules', to='vaccines.series')),
            ],
            options={
                'ordering': ['dependent_series', 'dependent_slot_number', 'anchor_series', 'anchor_slot_number'],
            },
        ),
    ]
