# Generated by Django 6.0.3 on 2026-03-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0011_policyversion_series_policy_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesTransitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_slot_number', models.PositiveIntegerField(blank=True, help_text='First slot number where this transition is allowed. Leave blank to allow from slot 1.', null=True)),
                ('end_slot_number', models.PositiveIntegerField(blank=True, help_text='Last slot number where this transition is allowed. Leave blank to allow indefinitely.', null=True)),
                ('allow_if_unavailable', models.BooleanField(default=False, help_text='If enabled, the transition is allowed only when the prior product is unavailable.')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_product', models.ForeignKey(blank=True, help_text='Optional source product. Leave blank to allow transition from any prior product in the series.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transition_rules', to='vaccines.product')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_rules', to='vaccines.series')),
                ('to_product', models.ForeignKey(help_text='Product that becomes allowed when this transition rule matches.', on_delete=django.db.models.deletion.CASCADE, related_name='to_transition_rules', to='vaccines.product')),
            ],
            options={
                'ordering': ['series', 'start_slot_number', 'to_product__vaccine__name'],
            },
        ),
    ]
