# Generated by Django 6.0.3 on 2026-03-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0012_seriestransitionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConstraintRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('constraint_type', models.CharField(choices=[('live_live_spacing', 'Live/live spacing')], max_length=50)),
                ('min_spacing_days', models.PositiveIntegerField(default=28)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('policy_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='global_constraints', to='vaccines.policyversion')),
            ],
            options={
                'ordering': ['constraint_type', 'name'],
            },
        ),
    ]
