# Generated by Django 6.0.3 on 2026-03-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0013_globalconstraintrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprule',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouprule',
            name='vaccine_to_give',
        ),
        migrations.AlterUniqueTogether(
            name='schedulerule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schedulerule',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='substitutionrule',
            name='substitute_vaccine',
        ),
        migrations.RemoveField(
            model_name='substitutionrule',
            name='target_vaccine',
        ),
        migrations.RemoveField(
            model_name='vaccinegroup',
            name='vaccines',
        ),
        migrations.RemoveField(
            model_name='series',
            name='legacy_group',
        ),
        migrations.DeleteModel(
            name='CatchupRule',
        ),
        migrations.DeleteModel(
            name='GroupRule',
        ),
        migrations.DeleteModel(
            name='ScheduleRule',
        ),
        migrations.DeleteModel(
            name='SubstitutionRule',
        ),
        migrations.DeleteModel(
            name='VaccineGroup',
        ),
    ]
