# Generated by Django 6.0.3 on 2026-03-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0014_remove_grouprule_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencyrule',
            name='is_coadmin',
            field=models.BooleanField(default=False, help_text='If enabled, missing anchor generates a co-administration warning instead of a block (block_if_anchor_missing should typically be false)'),
        ),
    ]
