# Generated by Django 6.0.3 on 2026-03-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0015_dependencyrule_is_coadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Contextual notes like catch-up rules or admin guidance', null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='display_name',
            field=models.CharField(blank=True, help_text="Full human-readable name, e.g. 'Pentavalent (DTP + HBV + Hib)'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='protects_against',
            field=models.TextField(blank=True, help_text='Comma-separated disease list shown in UI', null=True),
        ),
    ]
