# Generated by Django 6.0.3 on 2026-03-15 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0016_add_vaccine_human_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencyrule',
            name='anchor_product',
            field=models.ForeignKey(blank=True, help_text='Optional: Apply this rule only if the anchor was this specific product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchor_dependency_rules', to='vaccines.product'),
        ),
        migrations.AddField(
            model_name='dependencyrule',
            name='dependent_product',
            field=models.ForeignKey(blank=True, help_text='Optional: Apply this rule only when using this specific product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_dependency_rules', to='vaccines.product'),
        ),
    ]
