# Generated by Django 6.0.3 on 2026-03-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0017_dependencyrule_anchor_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriesrule',
            options={'ordering': ['series', 'prior_valid_doses', 'category', 'min_age_days', 'slot_number']},
        ),
        migrations.AddField(
            model_name='seriesrule',
            name='category',
            field=models.CharField(choices=[('routine', 'Routine (Standard Schedule)'), ('catchup', 'Catch-up (Late Vaccination)'), ('special', 'Special Case (Clinical Variations)')], default='routine', help_text='Categorize this rule for UI grouping and clinical context.', max_length=20),
        ),
    ]
