# Generated by Django 6.0.3 on 2026-03-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0018_alter_seriesrule_options_seriesrule_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('routine', 'Routine Schedule'), ('catchup', 'Catch-up / Late Start'), ('validation', 'Dose Validation'), ('dependency', 'Cross-Series Dependency'), ('edge_case', 'Edge Case'), ('regression', 'Bug Regression')], default='routine', max_length=20)),
                ('age_days', models.PositiveIntegerField(help_text='Age of the virtual patient in days')),
                ('history', models.JSONField(blank=True, default=list)),
                ('expected_due', models.JSONField(blank=True, default=list, help_text='List of vaccine names expected as DUE')),
                ('expected_upcoming', models.JSONField(blank=True, default=list, help_text='List of vaccine names expected as UPCOMING')),
                ('expected_missing', models.JSONField(blank=True, default=list, help_text='List of vaccine names expected as MISSING')),
                ('expected_blocked', models.JSONField(blank=True, default=list, help_text='List of vaccine names expected as BLOCKED')),
                ('expected_invalid', models.JSONField(blank=True, default=list, help_text='List of invalid dose specs: [{"vax": "Penta", "index": 1, "reason": "short_interval"}]')),
                ('last_status', models.CharField(choices=[('untested', 'Not Run Yet'), ('pass', 'Pass'), ('fail', 'Fail')], default='untested', max_length=10)),
                ('last_result', models.JSONField(blank=True, help_text='Structured diff from last run', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
