# Generated by Django 6.0.3 on 2026-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0019_testscenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('code', 'policy_version'), ('name', 'policy_version')},
        ),
    ]
