# Generated by Django 6.0.3 on 2026-03-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0020_alter_series_code_alter_series_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriestransitionrule',
            name='max_age_days',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum child age in days for this transition to apply. Leave blank for no maximum.', null=True),
        ),
        migrations.AddField(
            model_name='seriestransitionrule',
            name='min_age_days',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum child age in days for this transition to apply. Leave blank for no minimum.', null=True),
        ),
    ]
