# Generated by Django 6.0.3 on 2026-03-07 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.CharField(help_text='National ID or Medical Record Number', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, null=True)),
                ('parents_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
                ('unknown_status', models.BooleanField(default=False, help_text='Treat as unvaccinated if history is entirely unknown')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField()),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('administer_site', models.CharField(blank=True, max_length=100, null=True)),
                ('invalid_flag', models.BooleanField(default=False, help_text='Flagged if administered incorrectly (e.g. too early)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='patients.child')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_records', to='vaccines.vaccine')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
    ]
