# Generated by Django 6.0.3 on 2026-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='invalid_reason',
            field=models.CharField(blank=True, choices=[('too_early', 'Too Early (min age not met)'), ('too_late', 'Too Late (max age exceeded)'), ('short_interval', 'Interval Too Short'), ('wrong_vaccine', 'Wrong Vaccine for Age')], help_text='Structured reason code for why this dose is invalid', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='invalid_flag',
            field=models.BooleanField(default=False, help_text='Flagged if administered incorrectly'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Human-readable explanation of any issue', null=True),
        ),
    ]
