# Generated by Django 6.0.3 on 2026-03-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_vaccinationrecord_invalid_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='administered_elsewhere',
            field=models.BooleanField(default=False, help_text='Check if this dose was given at another facility (e.g. at birth in hospital) to avoid inflating local statistics.'),
        ),
    ]
