# Generated by Django 6.0.3 on 2026-03-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_vaccinationrecord_administered_elsewhere'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='warning_flag',
            field=models.BooleanField(default=False, help_text='Flagged if valid but has clinical warnings'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='warning_reason',
            field=models.TextField(blank=True, help_text='Explanation of clinical warnings', null=True),
        ),
    ]
