# Generated by Django 6.0.3 on 2026-03-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_vaccinationrecord_warning_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='warning_flag',
            field=models.BooleanField(default=False, help_text='Flagged with a soft warning (e.g. co-admin rule)'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='warning_reason',
            field=models.TextField(blank=True, help_text='Explanation for the warning', null=True),
        ),
    ]
